version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "requirements/dev.txt"}}-{{ checksum "requirements/prod.txt" }}
      - run:
          name: Install dependencies 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: dependencies-{{ checksum "requirements/dev.txt"}}-{{ checksum "requirements/prod.txt" }}
          paths: 
            - venv
  test:
    docker: 
      - image: circleci/python:3.8.5
        environment:
          DATABASE_URL: postgresql://myUsr:somePwd@localhost:5432/dbtest
          FLASK_APP: /home/circleci/repo/autoapp.py
          CONDUIT_SECRET: 'something-really-secret'
          FLASK_DEBUG: 1
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: myUsr
          POSTGRES_DB: dbtest
          POSTGRES_PASSWORD: somePwd
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements/dev.txt"}}-{{ .Environment.CACHE_VERSION }}
      - run: docker container run --name flask_db_test -e POSTGRES_PASSWORD=somePwd -e POSTGRES_USER=myUsr -p 5432:5432 -d dbtest
      - run: 
          name: sleep 1 
          command : dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: 
          name: run test
          command: |
            . venv/bin/activate
            flask db upgrade
            flask test
      - run: docker container stop flask_db_test
      - run: docker container rm flask_db_test
      - run: unset DATABASE_URL
  deploy-heroku:
    docker: 
      - image : buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
      - run:
          name: Smoke test
          command: |
            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/api/articles`
            if [ "$HTTPCODE" -ne 200 ];then
              echo "heroku app not responding, failing deploy"
              exit 1
            fi
  docker-build-and-push:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name:  build app image 
          command: |
            docker build --cache-from=app -t app .
      - run: 
          name: Publish app to docker hub
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker tag app $DOCKER_HUB_USERNAME/tp-devops-final-back:$CIRCLE_BUILD_NUM
            docker tag app $DOCKER_HUB_USERNAME/tp-devops-final-back:1.0
            docker push $DOCKER_HUB_USERNAME/tp-devops-final-back:$CIRCLE_BUILD_NUM
            docker push $DOCKER_HUB_USERNAME/tp-devops-final-back:1.0
workflows:
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-heroku:
          requires:
            - build
      - docker-build-and-push:
          requires:
            - build